// window._i18nLanguage = 
//  {
// // //     "zh": {
// // //         "Landing_01": "围绕DeFi和NFT经济设计的收益平台",
// // //         "Landing_02": "MOBOX平台将币安智能链(BSC)上的流动性挖矿与多年的游戏设计和开发经验相结合，创造了有史以来第一个免费玩轻松赚的区块链生态系统。",
        "Landing_05": "NFT经济体系",
        "Landing_06": "随着成千上万的NFTs等待着被打开，MOMO被赋予了挖掘MOBOX DAO 治理代币的功能。",
        "Landing_07": "MOBOX的奇幻世界",
        "Landing_09": "通过简洁的交互界面，用户只需要质押MOBOX平台支持的代币，其余的事情交给智能合约来执行就好。 让MOBOX与众不同的是流动性挖矿和游戏的结合，创造了一个真正的免费玩，轻松赚的区块链生态系统。 用户可以通过优化的流动性挖矿，NFT二级市场，在轻松享受乐趣的同时赚取超额收益！",
        "Landing_10": "2.什么是MBOX代币？",
        "Landing_11": "MBOX代币的总供应量为100,000,000枚， 用户可以将他们的NFTs进行质押来获得MBOX代币。进行质押的用户会获得十分诱人的激励，包括特殊的代币奖励，社区治理权限，还有更多的价值和功能。",
        "Landing_12": "3.什么是DeFi？",
        "Landing_13": "DeFi，也称为去中心化金融，是建立在区块链之上的金融应用程序。 MOBOX是建立在币安智能链上的，能给用户提供无缝跨链的完美区块链应用体验。",
        "Landing_14": "4.什么是NFT？",
        "Landing_15": "NFT，也称为非同质化代币，是一个独特的代币，不同于同质化加密资产无差别可互换，NFT中每一个非同质化代币都是特殊的。MOMO NFTs使用BRC20和BRC1155标准，这些特殊的NFTs可以在MOBOX生态系统所有游戏应用中使用。",
        "Landing_16": "免费玩，轻松赚",
        "Landing_17": "开始",
        "Landing_18": "详情",
        "Landing_19": "小黄鸟",
        "Landing_20": "疾速黄金鸟",
        "Landing_21": "白头鹰",
        "Landing_22": "上将白头鹰",
        "Landing_23": "蓝孔雀",
        "Landing_24": "宝石蓝孔雀",
        "Landing_25": "蜜蜂鸟",
        "Landing_26": "花仙蜜蜂鸟",
        "Landing_27": "绿雉鸟",
        "Landing_28": "影武者绿雉",
        "Landing_29": "小公鸡",
        "Landing_30": "愤怒铁公鸡",
        "Landing_31": "小白鸭",
        "Landing_32": "北京大白鸭",
        "Landing_33": "火烈鸟",
        "Landing_34": "时尚火烈鸟",
        "Landing_35": "帝企鹅",
        "Landing_36": "南极帝企鹅",
        "Landing_37": "小海鹦",
        "Landing_38": "北极光海鹦",
        "Landing_39": "小野猪",
        "Landing_40": "山大王野猪",
        "Landing_41": "小奶牛",
        "Landing_42": "狂野西部牛仔",
        "Landing_43": "小猪猪",
        "Landing_44": "食神",
        "Landing_45": "北极熊",
        "Landing_46": "极地北极熊",
        "Landing_47": "小海狮",
        "Landing_48": "大力水手海狮",
        "Landing_49": "鲨鱼",
        "Landing_50": "海盗王鲨鱼",
        "Landing_51": "珊瑚鱼",
        "Landing_52": "菲尔普斯",
        "Landing_53": "小丑鱼",
        "Landing_54": "攀登者尼莫",
        "Landing_55": "金鼓鱼",
        "Landing_56": "舰长金鼓鱼",
        "Landing_57": "小恶魔",
        "Landing_58": "地狱男爵",
        "Landing_59": "橙魔怪",
        "Landing_60": "地狱使者",
        "Landing_61": "花草怪",
        "Landing_62": "妙娃花草兽",
        "Landing_63": "西瓜怪",
        "Landing_64": "马屁西瓜兽",
        "Landing_65": "青翼怪",
        "Landing_66": "高帽青翼兽",
        "Landing_67": "MOMO不仅可以在二级市场上买卖，并能在所有MOBOX平台上开发的游戏中使用。独特的NFT经济体系设计从而赋予MOMO更多的价值。"
    },
    "en": {
        "Landing_01": "EARNING PLATFORM DESIGNED AROUND DEFI AND NFT ECONOMY",
        "Landing_02": "The MOBOX platform combines yield farming on the Binance Smart Chain (BSC) with years of game design and development experience, creating the first ever free to play - play to earn ecosystem.",
        "Landing_03": "BINANCE SMART CHAIN - OPTMIZED YIELD FARMING",
        "Landing_04": "Powered by the Binance Smart Chain, Team MOBOX’s optimized Yield Farming Smart Contracts provides the highest yield and lowest fees across the Binance ecosystem.",
        "Landing_05": "NFT ECONOMY",
        "Landing_06": "With over thousands of NFTs waiting to be unlocked, MOMO’s are brought to life empowering users to mine MOBOX DAO Tokens. ",
        "Landing_07": "THE WORLD OF MOBOX",
        "Landing_08": "1.How to earn on the MOBOX platform?",
        "Landing_09": "By keeping it simple, users only need to stake MOBOX platform supported tokens and let the Smart Contracts to the rest.  What sets MOBOX apart from everyone else is the combination of yield farming and gaming creating a truly Free to Play Play to Earn ecosystem.  Users are able to earn through optimized Yield Farming, secondary NFT market, and simply just by having fun!",
        "Landing_10": "2.What is the MBOX Token?",
        "Landing_11": "The MBOX token has a total supply of 100,000,000.  Users can stake their NFTs to farm MBOX tokens that provides them with a plethora of incentives such as special bonuses, governance, and much more.",
        "Landing_12": "3.What is DeFi?",
        "Landing_13": "DeFi or Decentralized Finance is a set of financial applications built on top of a blockchain.  MOBOX is built on top of the Binance Smart Chain, giving users a seamless blockchain experience.",
        "Landing_14": "4.What is NFT?",
        "Landing_15": "NFT or Non-Fungible Tokens is a unique token where each and everyone is special in itself. By utilizing BRC20 and BRC1155 standards for MOMO NFTs, these special tokens can be used across all games in the MOBOX ecosystem. ",
        "Landing_16": "FREE TO PLAY",
        "Landing_17": "PLAY",
        "Landing_18": "ABOUT",
        "Landing_19": "Tweets",
        "Landing_20": "Tweetser",
        "Landing_21": "Snowie flyer",
        "Landing_22": "Sir Snowington flyer",
        "Landing_23": "Bluey featherington",
        "Landing_24": "Bluesette featherington",
        "Landing_25": "Lei Lei Hawaiian-blue",
        "Landing_26": "Leilani Hawaiian blue hula",
        "Landing_27": "Mini Victory bluebird",
        "Landing_28": "Vicktorious the bluebird",
        "Landing_29": "Roosty Dood",
        "Landing_30": "Rooster Doodle - Doo",
        "Landing_31": "Quack",
        "Landing_32": "Quackers",
        "Landing_33": "Flamingy Flamingos",
        "Landing_34": "Flaminglatina Flamingos",
        "Landing_35": "Chilly la Penguino",
        "Landing_36": "Chillington la Penguino",
        "Landing_37": "Iggy pingi",
        "Landing_38": "Igloo penguinton",
        "Landing_39": "Oinkie",
        "Landing_40": "Captain Oinksly",
        "Landing_41": "Ango the calf",
        "Landing_42": "Sheriff Angus The Cow",
        "Landing_43": "Pigsly",
        "Landing_44": "Chef P.I.G",
        "Landing_45": "Cub Pooky",
        "Landing_46": "Polar Pook",
        "Landing_47": "Sealee",
        "Landing_48": "Admiral Sea Lion",
        "Landing_49": "Jabber",
        "Landing_50": "jabberjaws",
        "Landing_51": "Bree",
        "Landing_52": "Breezer",
        "Landing_53": "Sunny",
        "Landing_54": "Sunny Ray",
        "Landing_55": "Pop",
        "Landing_56": "El Capitan popitto",
        "Landing_57": "Demmie",
        "Landing_58": "Demon Dave",
        "Landing_59": "Jacko Junior",
        "Landing_60": "Jacko Senior",
        "Landing_61": "Leefatine",
        "Landing_62": "Leefalicious",
        "Landing_63": "Kiki",
        "Landing_64": "Kikatoro",
        "Landing_65": "Merly",
        "Landing_66": "Merlin the Great",
        "Landing_67": "With over thousands of NFTs waiting to be unlocked, MOMO’s are brought to life empowering users to mine MOBOX DAO Tokens. "
    },
    "fr": {
        "Landing_01": "EARNING PLATFORM DESIGNED AROUND DEFI AND NFT ECONOMY",
        "Landing_02": "The MOBOX platform combines yield farming on the Binance Smart Chain (BSC) with years of game design and development experience, creating the first ever free to play - play to earn ecosystem.",
        "Landing_03": "BINANCE SMART CHAIN - OPTMIZED YIELD FARMING",
        "Landing_04": "Powered by the Binance Smart Chain, Team MOBOX’s optimized Yield Farming Smart Contracts provides the highest yield and lowest fees across the Binance ecosystem.",
        "Landing_05": "NFT ECONOMY",
        "Landing_06": "With over thousands of NFTs waiting to be unlocked, MOMO’s are brought to life empowering users to mine MOBOX DAO Tokens. ",
        "Landing_07": "THE WORLD OF MOBOX",
        "Landing_08": "1.How to earn on the MOBOX platform?",
        "Landing_09": "By keeping it simple, users only need to stake MOBOX platform supported tokens and let the Smart Contracts to the rest.  What sets MOBOX apart from everyone else is the combination of yield farming and gaming creating a truly Free to Play Play to Earn ecosystem.  Users are able to earn through optimized Yield Farming, secondary NFT market, and simply just by having fun!",
        "Landing_10": "2.What is the MBOX Token?",
        "Landing_11": "The MBOX token has a total supply of 100,000,000.  Users can stake their NFTs to farm MBOX tokens that provides them with a plethora of incentives such as special bonuses, governance, and much more.",
        "Landing_12": "3.What is DeFi?",
        "Landing_13": "DeFi or Decentralized Finance is a set of financial applications built on top of a blockchain.  MOBOX is built on top of the Binance Smart Chain, giving users a seamless blockchain experience.",
        "Landing_14": "4.What is NFT?",
        "Landing_15": "NFT or Non-Fungible Tokens is a unique token where each and everyone is special in itself. By utilizing BRC20 and BRC1156 standards for MOMO NFTs, these special tokens can be used across all games in the MOBOX ecosystem.",
        "Landing_16": "FREE TO PLAY",
        "Landing_17": "PLAY",
        "Landing_18": "ABOUT",
        "Landing_19": "Tweets",
        "Landing_20": "Tweetser",
        "Landing_21": "Snowie flyer",
        "Landing_22": "Sir Snowington flyer",
        "Landing_23": "Bluey featherington",
        "Landing_24": "Bluesette featherington",
        "Landing_25": "Lei Lei Hawaiian-blue",
        "Landing_26": "Leilani Hawaiian blue hula",
        "Landing_27": "Mini Victory bluebird",
        "Landing_28": "Vicktorious the bluebird",
        "Landing_29": "Roosty Dood",
        "Landing_30": "Rooster Doodle - Doo",
        "Landing_31": "Quack",
        "Landing_32": "Quackers",
        "Landing_33": "Flamingy Flamingos",
        "Landing_34": "Flaminglatina Flamingos",
        "Landing_35": "Chilly la Penguino",
        "Landing_36": "Chillington la Penguino",
        "Landing_37": "Iggy pingi",
        "Landing_38": "Igloo penguinton",
        "Landing_39": "Oinkie",
        "Landing_40": "Captain Oinksly",
        "Landing_41": "Ango the calf",
        "Landing_42": "Sheriff Angus The Cow",
        "Landing_43": "Pigsly",
        "Landing_44": "Chef P.I.G",
        "Landing_45": "Cub Pooky",
        "Landing_46": "Polar Pook",
        "Landing_47": "Sealee",
        "Landing_48": "Admiral Sea Lion",
        "Landing_49": "Jabber",
        "Landing_50": "jabberjaws",
        "Landing_51": "Bree",
        "Landing_52": "Breezer",
        "Landing_53": "Sunny",
        "Landing_54": "Sunny Ray",
        "Landing_55": "Pop",
        "Landing_56": "El Capitan popitto",
        "Landing_57": "Demmie",
        "Landing_58": "Demon Dave",
        "Landing_59": "Jacko Junior",
        "Landing_60": "Jacko Senior",
        "Landing_61": "Leefatine",
        "Landing_62": "Leefalicious",
        "Landing_63": "Kiki",
        "Landing_64": "Kikatoro",
        "Landing_65": "Merly",
        "Landing_66": "Merlin the Great",
        "Landing_67": "With over thousands of NFTs waiting to be unlocked, MOMO’s are brought to life empowering users to mine MOBOX DAO Tokens. "
    },
    "de": {
        "Landing_01": "EARNING PLATFORM DESIGNED AROUND DEFI AND NFT ECONOMY",
        "Landing_02": "The MOBOX platform combines yield farming on the Binance Smart Chain (BSC) with years of game design and development experience, creating the first ever free to play - play to earn ecosystem.",
        "Landing_03": "BINANCE SMART CHAIN - OPTMIZED YIELD FARMING",
        "Landing_04": "Powered by the Binance Smart Chain, Team MOBOX’s optimized Yield Farming Smart Contracts provides the highest yield and lowest fees across the Binance ecosystem.",
        "Landing_05": "NFT ECONOMY",
        "Landing_06": "With over thousands of NFTs waiting to be unlocked, MOMO’s are brought to life empowering users to mine MOBOX DAO Tokens. ",
        "Landing_07": "THE WORLD OF MOBOX",
        "Landing_08": "1.How to earn on the MOBOX platform?",
        "Landing_09": "By keeping it simple, users only need to stake MOBOX platform supported tokens and let the Smart Contracts to the rest.  What sets MOBOX apart from everyone else is the combination of yield farming and gaming creating a truly Free to Play Play to Earn ecosystem.  Users are able to earn through optimized Yield Farming, secondary NFT market, and simply just by having fun!",
        "Landing_10": "2.What is the MBOX Token?",
        "Landing_11": "The MBOX token has a total supply of 100,000,000.  Users can stake their NFTs to farm MBOX tokens that provides them with a plethora of incentives such as special bonuses, governance, and much more.",
        "Landing_12": "3.What is DeFi?",
        "Landing_13": "DeFi or Decentralized Finance is a set of financial applications built on top of a blockchain.  MOBOX is built on top of the Binance Smart Chain, giving users a seamless blockchain experience.",
        "Landing_14": "4.What is NFT?",
        "Landing_15": "NFT or Non-Fungible Tokens is a unique token where each and everyone is special in itself. By utilizing BRC20 and BRC1157 standards for MOMO NFTs, these special tokens can be used across all games in the MOBOX ecosystem.",
        "Landing_16": "FREE TO PLAY",
        "Landing_17": "PLAY",
        "Landing_18": "ABOUT",
        "Landing_19": "Tweets",
        "Landing_20": "Tweetser",
        "Landing_21": "Snowie flyer",
        "Landing_22": "Sir Snowington flyer",
        "Landing_23": "Bluey featherington",
        "Landing_24": "Bluesette featherington",
        "Landing_25": "Lei Lei Hawaiian-blue",
        "Landing_26": "Leilani Hawaiian blue hula",
        "Landing_27": "Mini Victory bluebird",
        "Landing_28": "Vicktorious the bluebird",
        "Landing_29": "Roosty Dood",
        "Landing_30": "Rooster Doodle - Doo",
        "Landing_31": "Quack",
        "Landing_32": "Quackers",
        "Landing_33": "Flamingy Flamingos",
        "Landing_34": "Flaminglatina Flamingos",
        "Landing_35": "Chilly la Penguino",
        "Landing_36": "Chillington la Penguino",
        "Landing_37": "Iggy pingi",
        "Landing_38": "Igloo penguinton",
        "Landing_39": "Oinkie",
        "Landing_40": "Captain Oinksly",
        "Landing_41": "Ango the calf",
        "Landing_42": "Sheriff Angus The Cow",
        "Landing_43": "Pigsly",
        "Landing_44": "Chef P.I.G",
        "Landing_45": "Cub Pooky",
        "Landing_46": "Polar Pook",
        "Landing_47": "Sealee",
        "Landing_48": "Admiral Sea Lion",
        "Landing_49": "Jabber",
        "Landing_50": "jabberjaws",
        "Landing_51": "Bree",
        "Landing_52": "Breezer",
        "Landing_53": "Sunny",
        "Landing_54": "Sunny Ray",
        "Landing_55": "Pop",
        "Landing_56": "El Capitan popitto",
        "Landing_57": "Demmie",
        "Landing_58": "Demon Dave",
        "Landing_59": "Jacko Junior",
        "Landing_60": "Jacko Senior",
        "Landing_61": "Leefatine",
        "Landing_62": "Leefalicious",
        "Landing_63": "Kiki",
        "Landing_64": "Kikatoro",
        "Landing_65": "Merly",
        "Landing_66": "Merlin the Great",
        "Landing_67": "With over thousands of NFTs waiting to be unlocked, MOMO’s are brought to life empowering users to mine MOBOX DAO Tokens. "
    },
    "es": {
        "Landing_01": "EARNING PLATFORM DESIGNED AROUND DEFI AND NFT ECONOMY",
        "Landing_02": "The MOBOX platform combines yield farming on the Binance Smart Chain (BSC) with years of game design and development experience, creating the first ever free to play - play to earn ecosystem.",
        "Landing_03": "BINANCE SMART CHAIN - OPTMIZED YIELD FARMING",
        "Landing_04": "Powered by the Binance Smart Chain, Team MOBOX’s optimized Yield Farming Smart Contracts provides the highest yield and lowest fees across the Binance ecosystem.",
        "Landing_05": "NFT ECONOMY",
        "Landing_06": "With over thousands of NFTs waiting to be unlocked, MOMO’s are brought to life empowering users to mine MOBOX DAO Tokens. ",
        "Landing_07": "THE WORLD OF MOBOX",
        "Landing_08": "1.How to earn on the MOBOX platform?",
        "Landing_09": "By keeping it simple, users only need to stake MOBOX platform supported tokens and let the Smart Contracts to the rest.  What sets MOBOX apart from everyone else is the combination of yield farming and gaming creating a truly Free to Play Play to Earn ecosystem.  Users are able to earn through optimized Yield Farming, secondary NFT market, and simply just by having fun!",
        "Landing_10": "2.What is the MBOX Token?",
        "Landing_11": "The MBOX token has a total supply of 100,000,000.  Users can stake their NFTs to farm MBOX tokens that provides them with a plethora of incentives such as special bonuses, governance, and much more.",
        "Landing_12": "3.What is DeFi?",
        "Landing_13": "DeFi or Decentralized Finance is a set of financial applications built on top of a blockchain.  MOBOX is built on top of the Binance Smart Chain, giving users a seamless blockchain experience.",
        "Landing_14": "4.What is NFT?",
        "Landing_15": "NFT or Non-Fungible Tokens is a unique token where each and everyone is special in itself. By utilizing BRC20 and BRC1158 standards for MOMO NFTs, these special tokens can be used across all games in the MOBOX ecosystem.",
        "Landing_16": "FREE TO PLAY",
        "Landing_17": "PLAY",
        "Landing_18": "ABOUT",
        "Landing_19": "Tweets",
        "Landing_20": "Tweetser",
        "Landing_21": "Snowie flyer",
        "Landing_22": "Sir Snowington flyer",
        "Landing_23": "Bluey featherington",
        "Landing_24": "Bluesette featherington",
        "Landing_25": "Lei Lei Hawaiian-blue",
        "Landing_26": "Leilani Hawaiian blue hula",
        "Landing_27": "Mini Victory bluebird",
        "Landing_28": "Vicktorious the bluebird",
        "Landing_29": "Roosty Dood",
        "Landing_30": "Rooster Doodle - Doo",
        "Landing_31": "Quack",
        "Landing_32": "Quackers",
        "Landing_33": "Flamingy Flamingos",
        "Landing_34": "Flaminglatina Flamingos",
        "Landing_35": "Chilly la Penguino",
        "Landing_36": "Chillington la Penguino",
        "Landing_37": "Iggy pingi",
        "Landing_38": "Igloo penguinton",
        "Landing_39": "Oinkie",
        "Landing_40": "Captain Oinksly",
        "Landing_41": "Ango the calf",
        "Landing_42": "Sheriff Angus The Cow",
        "Landing_43": "Pigsly",
        "Landing_44": "Chef P.I.G",
        "Landing_45": "Cub Pooky",
        "Landing_46": "Polar Pook",
        "Landing_47": "Sealee",
        "Landing_48": "Admiral Sea Lion",
        "Landing_49": "Jabber",
        "Landing_50": "jabberjaws",
        "Landing_51": "Bree",
        "Landing_52": "Breezer",
        "Landing_53": "Sunny",
        "Landing_54": "Sunny Ray",
        "Landing_55": "Pop",
        "Landing_56": "El Capitan popitto",
        "Landing_57": "Demmie",
        "Landing_58": "Demon Dave",
        "Landing_59": "Jacko Junior",
        "Landing_60": "Jacko Senior",
        "Landing_61": "Leefatine",
        "Landing_62": "Leefalicious",
        "Landing_63": "Kiki",
        "Landing_64": "Kikatoro",
        "Landing_65": "Merly",
        "Landing_66": "Merlin the Great",
        "Landing_67": "With over thousands of NFTs waiting to be unlocked, MOMO’s are brought to life empowering users to mine MOBOX DAO Tokens. "
    },
    "ru": {
        "Landing_01": "EARNING PLATFORM DESIGNED AROUND DEFI AND NFT ECONOMY",
        "Landing_02": "The MOBOX platform combines yield farming on the Binance Smart Chain (BSC) with years of game design and development experience, creating the first ever free to play - play to earn ecosystem.",
        "Landing_03": "BINANCE SMART CHAIN - OPTMIZED YIELD FARMING",
        "Landing_04": "Powered by the Binance Smart Chain, Team MOBOX’s optimized Yield Farming Smart Contracts provides the highest yield and lowest fees across the Binance ecosystem.",
        "Landing_05": "NFT ECONOMY",
        "Landing_06": "With over thousands of NFTs waiting to be unlocked, MOMO’s are brought to life empowering users to mine MOBOX DAO Tokens. ",
        "Landing_07": "THE WORLD OF MOBOX",
        "Landing_08": "1.How to earn on the MOBOX platform?",
        "Landing_09": "By keeping it simple, users only need to stake MOBOX platform supported tokens and let the Smart Contracts to the rest.  What sets MOBOX apart from everyone else is the combination of yield farming and gaming creating a truly Free to Play Play to Earn ecosystem.  Users are able to earn through optimized Yield Farming, secondary NFT market, and simply just by having fun!",
        "Landing_10": "2.What is the MBOX Token?",
        "Landing_11": "The MBOX token has a total supply of 100,000,000.  Users can stake their NFTs to farm MBOX tokens that provides them with a plethora of incentives such as special bonuses, governance, and much more.",
        "Landing_12": "3.What is DeFi?",
        "Landing_13": "DeFi or Decentralized Finance is a set of financial applications built on top of a blockchain.  MOBOX is built on top of the Binance Smart Chain, giving users a seamless blockchain experience.",
        "Landing_14": "4.What is NFT?",
        "Landing_15": "NFT or Non-Fungible Tokens is a unique token where each and everyone is special in itself. By utilizing BRC20 and BRC1159 standards for MOMO NFTs, these special tokens can be used across all games in the MOBOX ecosystem.",
        "Landing_16": "FREE TO PLAY",
        "Landing_17": "PLAY",
        "Landing_18": "ABOUT",
        "Landing_19": "Tweets",
        "Landing_20": "Tweetser",
        "Landing_21": "Snowie flyer",
        "Landing_22": "Sir Snowington flyer",
        "Landing_23": "Bluey featherington",
        "Landing_24": "Bluesette featherington",
        "Landing_25": "Lei Lei Hawaiian-blue",
        "Landing_26": "Leilani Hawaiian blue hula",
        "Landing_27": "Mini Victory bluebird",
        "Landing_28": "Vicktorious the bluebird",
        "Landing_29": "Roosty Dood",
        "Landing_30": "Rooster Doodle - Doo",
        "Landing_31": "Quack",
        "Landing_32": "Quackers",
        "Landing_33": "Flamingy Flamingos",
        "Landing_34": "Flaminglatina Flamingos",
        "Landing_35": "Chilly la Penguino",
        "Landing_36": "Chillington la Penguino",
        "Landing_37": "Iggy pingi",
        "Landing_38": "Igloo penguinton",
        "Landing_39": "Oinkie",
        "Landing_40": "Captain Oinksly",
        "Landing_41": "Ango the calf",
        "Landing_42": "Sheriff Angus The Cow",
        "Landing_43": "Pigsly",
        "Landing_44": "Chef P.I.G",
        "Landing_45": "Cub Pooky",
        "Landing_46": "Polar Pook",
        "Landing_47": "Sealee",
        "Landing_48": "Admiral Sea Lion",
        "Landing_49": "Jabber",
        "Landing_50": "jabberjaws",
        "Landing_51": "Bree",
        "Landing_52": "Breezer",
        "Landing_53": "Sunny",
        "Landing_54": "Sunny Ray",
        "Landing_55": "Pop",
        "Landing_56": "El Capitan popitto",
        "Landing_57": "Demmie",
        "Landing_58": "Demon Dave",
        "Landing_59": "Jacko Junior",
        "Landing_60": "Jacko Senior",
        "Landing_61": "Leefatine",
        "Landing_62": "Leefalicious",
        "Landing_63": "Kiki",
        "Landing_64": "Kikatoro",
        "Landing_65": "Merly",
        "Landing_66": "Merlin the Great",
        "Landing_67": "With over thousands of NFTs waiting to be unlocked, MOMO’s are brought to life empowering users to mine MOBOX DAO Tokens. "
    },
    "jp": {
        "Landing_01": "EARNING PLATFORM DESIGNED AROUND DEFI AND NFT ECONOMY",
        "Landing_02": "The MOBOX platform combines yield farming on the Binance Smart Chain (BSC) with years of game design and development experience, creating the first ever free to play - play to earn ecosystem.",
        "Landing_03": "BINANCE SMART CHAIN - OPTMIZED YIELD FARMING",
        "Landing_04": "Powered by the Binance Smart Chain, Team MOBOX’s optimized Yield Farming Smart Contracts provides the highest yield and lowest fees across the Binance ecosystem.",
        "Landing_05": "NFT ECONOMY",
        "Landing_06": "With over thousands of NFTs waiting to be unlocked, MOMO’s are brought to life empowering users to mine MOBOX DAO Tokens. ",
        "Landing_07": "THE WORLD OF MOBOX",
        "Landing_08": "1.How to earn on the MOBOX platform?",
        "Landing_09": "By keeping it simple, users only need to stake MOBOX platform supported tokens and let the Smart Contracts to the rest.  What sets MOBOX apart from everyone else is the combination of yield farming and gaming creating a truly Free to Play Play to Earn ecosystem.  Users are able to earn through optimized Yield Farming, secondary NFT market, and simply just by having fun!",
        "Landing_10": "2.What is the MBOX Token?",
        "Landing_11": "The MBOX token has a total supply of 100,000,000.  Users can stake their NFTs to farm MBOX tokens that provides them with a plethora of incentives such as special bonuses, governance, and much more.",
        "Landing_12": "3.What is DeFi?",
        "Landing_13": "DeFi or Decentralized Finance is a set of financial applications built on top of a blockchain.  MOBOX is built on top of the Binance Smart Chain, giving users a seamless blockchain experience.",
        "Landing_14": "4.What is NFT?",
        "Landing_15": "NFT or Non-Fungible Tokens is a unique token where each and everyone is special in itself. By utilizing BRC20 and BRC1160 standards for MOMO NFTs, these special tokens can be used across all games in the MOBOX ecosystem.",
        "Landing_16": "FREE TO PLAY",
        "Landing_17": "PLAY",
        "Landing_18": "ABOUT",
        "Landing_19": "Tweets",
        "Landing_20": "Tweetser",
        "Landing_21": "Snowie flyer",
        "Landing_22": "Sir Snowington flyer",
        "Landing_23": "Bluey featherington",
        "Landing_24": "Bluesette featherington",
        "Landing_25": "Lei Lei Hawaiian-blue",
        "Landing_26": "Leilani Hawaiian blue hula",
        "Landing_27": "Mini Victory bluebird",
        "Landing_28": "Vicktorious the bluebird",
        "Landing_29": "Roosty Dood",
        "Landing_30": "Rooster Doodle - Doo",
        "Landing_31": "Quack",
        "Landing_32": "Quackers",
        "Landing_33": "Flamingy Flamingos",
        "Landing_34": "Flaminglatina Flamingos",
        "Landing_35": "Chilly la Penguino",
        "Landing_36": "Chillington la Penguino",
        "Landing_37": "Iggy pingi",
        "Landing_38": "Igloo penguinton",
        "Landing_39": "Oinkie",
        "Landing_40": "Captain Oinksly",
        "Landing_41": "Ango the calf",
        "Landing_42": "Sheriff Angus The Cow",
        "Landing_43": "Pigsly",
        "Landing_44": "Chef P.I.G",
        "Landing_45": "Cub Pooky",
        "Landing_46": "Polar Pook",
        "Landing_47": "Sealee",
        "Landing_48": "Admiral Sea Lion",
        "Landing_49": "Jabber",
        "Landing_50": "jabberjaws",
        "Landing_51": "Bree",
        "Landing_52": "Breezer",
        "Landing_53": "Sunny",
        "Landing_54": "Sunny Ray",
        "Landing_55": "Pop",
        "Landing_56": "El Capitan popitto",
        "Landing_57": "Demmie",
        "Landing_58": "Demon Dave",
        "Landing_59": "Jacko Junior",
        "Landing_60": "Jacko Senior",
        "Landing_61": "Leefatine",
        "Landing_62": "Leefalicious",
        "Landing_63": "Kiki",
        "Landing_64": "Kikatoro",
        "Landing_65": "Merly",
        "Landing_66": "Merlin the Great",
        "Landing_67": "With over thousands of NFTs waiting to be unlocked, MOMO’s are brought to life empowering users to mine MOBOX DAO Tokens. "
    },
    "kr": {
        "Landing_01": "Defi 및 NFT 경제성을 중심으로 설계된 수익 플랫폼",
        "Landing_02": "모박스 플랫폼은 바이낸스 스마트체인(BSC)의 yield farming과 다년간의 게임 설계 및 개발 경험을 결합해, 최초로 생태계를 무료로 즐기며 수익을 내는 플레이를 구현했습니다.",
        "Landing_03": "바이낸스 스마트 체인 - 일드파밍 최적화",
        "Landing_04": "바이낸스 스마트 체인에 기반한 팀 MOBOX의 최적화된  일드파밍 스마트 계약은 바이낸스 생태계 전반에 걸쳐 최고 수익률과 최저 수수료를 제공합니다.",
        "Landing_05": "NFT 경제",
        "Landing_06": "수천 개 이상의 NFT가 잠금 해제되기를 기다리는 가운데, MOMO는 사용자들이 MOBOX DAO 토큰을 채굴할 수 있도록 힘을 실어주고 있습니다.",
        "Landing_07": "모박스 세계",
        "Landing_08": "1. MOBOX 플랫폼에서 어떻게 수익을 올릴 수 있나요?",
        "Landing_09": "단순성을 유지함으로써 사용자는 MOBOX 플랫폼 지원 토큰만 보유하면 되고 나머지는 스마트 컨트랙트만 보유하면 됩니다.  MOBOX가 다른 모든 사람들과 차별화되는 것은 일드파밍과 게임의 조합으로 진정한 무료 게임 환경을 조성한다는 것입니다.  사용자는 최적화된 일드파밍, 2차 NFT 시장을 통해 단순히 재미를 통해 수익을 올릴 수 있습니다!",
        "Landing_10": "2. MBOX 토큰이란 무엇인가요?",
        "Landing_11": "MBOX 토큰의 총 공급량은 1,000,000,000입니다.  사용자는 자신의 NFT를 MBOX 토큰 농장에 스테이킹 할 수 있으며, MBOX 토큰은 특별 상여금, 거버넌스 등과 같은 다양한 인센티브를 제공합니다.",
        "Landing_12": "3. 디파이가 뭐예요?",
        "Landing_13": "디파이(Depolidated Finance)는 블록체인 위에 구축된 금융 애플리케이션 집합입니다.  모박스는 바이낸스 스마트체인 위에 구축되어 있어 사용자에게 원활한 블록체인 경험을 제공합니다.",
        "Landing_14": "4. NFT란 무엇입니까?",
        "Landing_15": "NFT는 그 자체로 하나하나가 특별한 독특한 토큰입니다. MOMO NFT에 대한 BRC20과 BRC1155 표준을 활용하여 MOBOX 생태계의 모든 게임에 사용할 수 있습니다.",
        "Landing_16": "FREE TO PLAY",
        "Landing_17": "플레이",
        "Landing_18": "약",
        "Landing_19": "Tweets",
        "Landing_20": "Tweetser",
        "Landing_21": "Snowie flyer",
        "Landing_22": "Sir Snowington flyer",
        "Landing_23": "Bluey featherington",
        "Landing_24": "Bluesette featherington",
        "Landing_25": "Lei Lei Hawaiian-blue",
        "Landing_26": "Leilani Hawaiian blue hula",
        "Landing_27": "Mini Victory bluebird",
        "Landing_28": "Vicktorious the bluebird",
        "Landing_29": "Roosty Dood",
        "Landing_30": "Rooster Doodle - Doo",
        "Landing_31": "Quack",
        "Landing_32": "Quackers",
        "Landing_33": "Flamingy Flamingos",
        "Landing_34": "Flaminglatina Flamingos",
        "Landing_35": "Chilly la Penguino",
        "Landing_36": "Chillington la Penguino",
        "Landing_37": "Iggy pingi",
        "Landing_38": "Igloo penguinton",
        "Landing_39": "Oinkie",
        "Landing_40": "Captain Oinksly",
        "Landing_41": "Ango the calf",
        "Landing_42": "Sheriff Angus The Cow",
        "Landing_43": "Pigsly",
        "Landing_44": "Chef P.I.G",
        "Landing_45": "Cub Pooky",
        "Landing_46": "Polar Pook",
        "Landing_47": "Sealee",
        "Landing_48": "Admiral Sea Lion",
        "Landing_49": "Jabber",
        "Landing_50": "jabberjaws",
        "Landing_51": "Bree",
        "Landing_52": "Breezer",
        "Landing_53": "Sunny",
        "Landing_54": "Sunny Ray",
        "Landing_55": "Pop",
        "Landing_56": "El Capitan popitto",
        "Landing_57": "Demmie",
        "Landing_58": "Demon Dave",
        "Landing_59": "Jacko Junior",
        "Landing_60": "Jacko Senior",
        "Landing_61": "Leefatine",
        "Landing_62": "Leefalicious",
        "Landing_63": "Kiki",
        "Landing_64": "Kikatoro",
        "Landing_65": "Merly",
        "Landing_66": "Merlin the Great",
        "Landing_67": " 모모도 2차 시장에서 사고 팔 수 있고 MOBOX가 개발한 모든 게임 전반에 걸쳐 사용할 수 있어 이용자들에게 더욱 큰 수익력을 선사할 것입니다. "
    },
    "tw": {
        "Landing_01": "EARNING PLATFORM DESIGNED AROUND DEFI AND NFT ECONOMY",
        "Landing_02": "The MOBOX platform combines yield farming on the Binance Smart Chain (BSC) with years of game design and development experience, creating the first ever free to play - play to earn ecosystem.",
        "Landing_03": "BINANCE SMART CHAIN - OPTMIZED YIELD FARMING",
        "Landing_04": "Powered by the Binance Smart Chain, Team MOBOX’s optimized Yield Farming Smart Contracts provides the highest yield and lowest fees across the Binance ecosystem.",
        "Landing_05": "NFT ECONOMY",
        "Landing_06": "With over thousands of NFTs waiting to be unlocked, MOMO’s are brought to life empowering users to mine MOBOX DAO Tokens. ",
        "Landing_07": "THE WORLD OF MOBOX",
        "Landing_08": "1.How to earn on the MOBOX platform?",
        "Landing_09": "By keeping it simple, users only need to stake MOBOX platform supported tokens and let the Smart Contracts to the rest.  What sets MOBOX apart from everyone else is the combination of yield farming and gaming creating a truly Free to Play Play to Earn ecosystem.  Users are able to earn through optimized Yield Farming, secondary NFT market, and simply just by having fun!",
        "Landing_10": "2.What is the MBOX Token?",
        "Landing_11": "The MBOX token has a total supply of 100,000,000.  Users can stake their NFTs to farm MBOX tokens that provides them with a plethora of incentives such as special bonuses, governance, and much more.",
        "Landing_12": "3.What is DeFi?",
        "Landing_13": "DeFi or Decentralized Finance is a set of financial applications built on top of a blockchain.  MOBOX is built on top of the Binance Smart Chain, giving users a seamless blockchain experience.",
        "Landing_14": "4.What is NFT?",
        "Landing_15": "NFT or Non-Fungible Tokens is a unique token where each and everyone is special in itself. By utilizing BRC20 and BRC1160 standards for MOMO NFTs, these special tokens can be used across all games in the MOBOX ecosystem.",
        "Landing_16": "FREE TO PLAY",
        "Landing_17": "PLAY",
        "Landing_18": "ABOUT",
        "Landing_19": "Tweets",
        "Landing_20": "Tweetser",
        "Landing_21": "Snowie flyer",
        "Landing_22": "Sir Snowington flyer",
        "Landing_23": "Bluey featherington",
        "Landing_24": "Bluesette featherington",
        "Landing_25": "Lei Lei Hawaiian-blue",
        "Landing_26": "Leilani Hawaiian blue hula",
        "Landing_27": "Mini Victory bluebird",
        "Landing_28": "Vicktorious the bluebird",
        "Landing_29": "Roosty Dood",
        "Landing_30": "Rooster Doodle - Doo",
        "Landing_31": "Quack",
        "Landing_32": "Quackers",
        "Landing_33": "Flamingy Flamingos",
        "Landing_34": "Flaminglatina Flamingos",
        "Landing_35": "Chilly la Penguino",
        "Landing_36": "Chillington la Penguino",
        "Landing_37": "Iggy pingi",
        "Landing_38": "Igloo penguinton",
        "Landing_39": "Oinkie",
        "Landing_40": "Captain Oinksly",
        "Landing_41": "Ango the calf",
        "Landing_42": "Sheriff Angus The Cow",
        "Landing_43": "Pigsly",
        "Landing_44": "Chef P.I.G",
        "Landing_45": "Cub Pooky",
        "Landing_46": "Polar Pook",
        "Landing_47": "Sealee",
        "Landing_48": "Admiral Sea Lion",
        "Landing_49": "Jabber",
        "Landing_50": "jabberjaws",
        "Landing_51": "Bree",
        "Landing_52": "Breezer",
        "Landing_53": "Sunny",
        "Landing_54": "Sunny Ray",
        "Landing_55": "Pop",
        "Landing_56": "El Capitan popitto",
        "Landing_57": "Demmie",
        "Landing_58": "Demon Dave",
        "Landing_59": "Jacko Junior",
        "Landing_60": "Jacko Senior",
        "Landing_61": "Leefatine",
        "Landing_62": "Leefalicious",
        "Landing_63": "Kiki",
        "Landing_64": "Kikatoro",
        "Landing_65": "Merly",
        "Landing_66": "Merlin the Great",
        "Landing_67": "With over thousands of NFTs waiting to be unlocked, MOMO’s are brought to life empowering users to mine MOBOX DAO Tokens. "
    }
}return null;
return null;
